name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  intl: ^0.19.0
  fluttertoast: ^8.2.2
  firebase_core: ^3.13.1
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.8
  qr_flutter: ^4.1.0
  camera: ^0.10.5+5
  path_provider: ^2.1.5
  path: ^1.9.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Mokguide.png"  # 여기에 실제 아이콘 파일 경로 입력 (정사각형 PNG)

flutter:
  uses-material-design: true

  assets:
    - assets/Mokguide.png
    - assets/door.png
